---
- name: Loop Register Test
  gather_facts: false
  hosts:  localhost 
  tasks:
    - name: Looping Echo Task
      ansible.builtin.shell: "echo This is my item: {{ item }}"
      loop:
        - one
        - two
      register: echo_results1

    - name: Show echo_results variable
      ansible.builtin.debug:
        var: echo_results2