---
- name: Display specific ansible_facts
  hosts: webserver
  tasks:
    - name: Display specific facts
      ansible.builtin.debug:
        msg: >-
          Host '{{ ansible_facts["hostname"] }}' with Python
          version '{{ ansible_facts["python_version"] }}'
          has '{{ ansible_facts["processor_count"] }}'
          processors and '{{ ansible_facts["memtotal_mb"] }}'
          MiB of total system memory.
    - name: Display ansible_local variable
      ansible.builtin.debug:
        msg: >-
          The ansible_local variable is set to
          '{{ ansible_facts["ansible_local"] }}'